permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: dstreet
description: "Musings on development"
email: street.davide@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
repository: "https://github.com/dstreet"
url: "https://dstreet.github.io"
disqus_shortname: "davidstreetdesigns"
google_analytics: UA-7286719-5

# social footer
social:
  github:
    slug: github
    link: http://github.com/dstreet
  twitter:
    slug: twitter
    link: http://twitter.com/open_dave
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/david-street-552b7563
